name: Update GitHub Profile README

on:
  schedule:
    - cron: "0 */6 * * *"   # cada 6 horas
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest project (repo + description)
        id: latest
        run: |
          LATEST_JSON=$(curl -s "https://api.github.com/users/bguerraDev/repos?sort=updated&per_page=1")
          LATEST_REPO=$(echo "$LATEST_JSON" | jq -r '.[0].full_name')
          LATEST_DESC=$(curl -s "https://api.github.com/repos/$LATEST_REPO" | jq -r '.description // "No description"')
          echo "LATEST_REPO=$LATEST_REPO" >> $GITHUB_ENV
          echo "LATEST_DESC=$LATEST_DESC" >> $GITHUB_ENV

      - name: Get latest repositories list (5)
        id: list
        run: |
          REPO_LIST=$(curl -s "https://api.github.com/users/bguerraDev/repos?sort=updated&per_page=5" \
            | jq -r '.[] | "- [\(.name)](\(.html_url)) — \(.description // "No description")"')
          {
            echo "REPO_LIST<<'EOF'"
            echo "$REPO_LIST"
            echo "EOF"
          } >> $GITHUB_ENV

      - name: Update README sections (no sed)
        run: |
          node - <<'NODE'
          const fs = require('fs');

          const readme = fs.readFileSync('README.md', 'utf8');

          function replaceBetween(src, tag, content) {
            const start = `<!-- ${tag}:START -->`;
            const end   = `<!-- ${tag}:END -->`;
            const re = new RegExp(`${start}[\\s\\S]*?${end}`, 'm');
            return src.replace(re, `${start}\n${content}\n${end}`);
          }

          let latest = `🚀 **${process.env.LATEST_REPO}** — ${process.env.LATEST_DESC}`;
          let repos  = process.env.REPO_LIST;

          let out = readme;

          // Latest project
          out = replaceBetween(out, 'LATEST-PROJECT', latest);

          // Latest repositories (prefer our tag; if no tag, try the old activity tag)
          if (out.includes('<!-- LATEST-REPOS:START -->')) {
            out = replaceBetween(out, 'LATEST-REPOS', repos);
          } else if (out.includes('<!--START_SECTION:activity-->')) {
            const start = '<!--START_SECTION:activity-->';
            const end = '<!--END_SECTION:activity-->';
            const re = new RegExp(`${start}[\\s\\S]*?${end}`, 'm');
            out = out.replace(re, `${start}\n${repos}\n${end}`);
          }

          fs.writeFileSync('README.md', out);
          NODE

      - name: Commit and push changes
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update latest project and repos [skip ci]" || echo "No changes"
          git push